spring:
  application:
    name: gateway-server
  cloud:
    discovery:
      enabled: true
    gateway:
      gdefault-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: MS-AUTH
          uri: lb://ms-auth
          predicates:
            - Path=/api/*/auth/**

        - id: MS-PRODUCT
          uri: lb://ms-product
          predicates:
            - Path=/api/*/products/**

        - id: MS-ORDER
          uri: lb://ms-order
          predicates:
            - Path=/api/**
    loadbalancer:
      ribbon:
        enabled: false


eureka:
  client:
    fetch-registry: true
    service-url.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 5555

