server:
  port: 8085

spring:
  application:
    name: ms-order
  redis:
    host: redis-server
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 12345
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
      fetchRegistry: true
