server:
  port: 0

spring:
  application:
    name: ms-auth
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 12345
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true

